MIN_ALTITUDE = 300
MAX_ALTITUDE = 3000
MAX_SLOPE = 1.0
WIDTH_TANK = 30
HEIGHT_TANK = 12
LUMPINESS = 15
TEXTURE = 3.0

TANK_1_ASSET = "assets/tank_1.png"
CANNON_1_ASSET = "assets/cannon_1.png"
BULLET_1 = "assets/bullet_1.png"
TANK_2_ASSET = "assets/tank_2.png"
CANNON_2_ASSET = "assets/cannon_2.png"
BULLET_2 = "assets/bullet_2.png"

BULLET_SOUND = "assets/bullet_launch.wav"
MUSIC = "assets/tanks_music.wav"
WIN_SOUND = "assets/win_sound.wav"

GROUND_COLOR = (53, 40, 30)
BACKGROUND_COLOR = (70, 62, 82)

TANK_SCALE = 0.05
CANNON_SCALE = 0.02
BULLET_SCALE = 0.02
DISTANCE_BETWEEN_CANNON_TANK = 8

TIME_INTERVAL = 0.8

SMALL_ROTATION = 0.03
LARGE_ROTATION = 0.11

MUZZLE_VELOCITY = 700
PROJECTILE_MASS = 46.7
PROJECTILE_RADIUS = 0.077445

WINDOW_SIZE_X = 800
WINDOW_SIZE_Y = 600

PIXELS_TO_METERS = 40